version: "2.2"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./tmp/certs:/usr/share/elasticsearch/config/certs
      - ./tmp/cert_config/instance.yml:/tmp/cert_config/instance.yml
    user: "0"
    command: >
      bash -c '
        echo "Creating certs...";
        bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
        unzip config/certs/ca.zip -d config/certs;

        bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in /tmp/cert_config/instance.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
        unzip config/certs/certs.zip -d config/certs;
        echo "Creating done :)";
      '