filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/test/*
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  ssl.certificate_authorities:
    - /etc/filebeat/config/certs/ca/ca.crt
